import "./App.css";
import MapArea from "./components/Map";
import BroadCasterMap from "./components/BroadCasterMap";
import SingleStadium from "./components/SingleStadiumMap";
import MultipleStadium from "./components/MultipleStadiumMap";

function App() {
  const selectedCountries = [
    {
      country_id: 3,
      country_name: "Algeria",
      country_code: "DZA",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 6,
      country_name: "Angola",
      country_code: "AGO",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 7,
      country_name: "Anguilla",
      country_code: "AIA",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 216,
      country_name: "Antartica",
      country_code: "ATA",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 8,
      country_name: "Antigua and Barbuda",
      country_code: "ATG",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 9,
      country_name: "Argentina",
      country_code: "ARG",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 12,
      country_name: "Australia",
      country_code: "AUS",
      broadcast_details: {
        broadcasters: ["Stan Sport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Stan-Sport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 13,
      country_name: "Austria",
      country_code: "AUT",
      broadcast_details: {
        broadcasters: ["Morethansport"],
        s3_urls: [
          " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 15,
      country_name: "Bahamas",
      country_code: "BHS",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 16,
      country_name: "Bahrain",
      country_code: "BHR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 17,
      country_name: "Bangladesh",
      country_code: "BGD",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 18,
      country_name: "Barbados",
      country_code: "BRB",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 21,
      country_name: "Belize",
      country_code: "BLZ",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 22,
      country_name: "Benin",
      country_code: "BEN",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 23,
      country_name: "Bermuda",
      country_code: "BMU",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 24,
      country_name: "Bhutan",
      country_code: "BTN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 25,
      country_name: "Bolivia",
      country_code: "BOL",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 27,
      country_name: "Botswana",
      country_code: "BWA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 28,
      country_name: "Brazil",
      country_code: "BRA",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 29,
      country_name: "British Virgin Islands",
      country_code: "BVI",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 30,
      country_name: "Brunei",
      country_code: "BRN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 32,
      country_name: "Burkina Faso",
      country_code: "BFA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 33,
      country_name: "Burundi",
      country_code: "BDI",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 35,
      country_name: "Cambodia",
      country_code: "KHM",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 36,
      country_name: "Cameroon",
      country_code: "CMR",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 37,
      country_name: "Canada",
      country_code: "CAN",
      broadcast_details: {
        broadcasters: ["Sportsnet"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Sportsnet.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 34,
      country_name: "Cape Verde",
      country_code: "CPV",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 38,
      country_name: "Cayman Islands",
      country_code: "CYM",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 40,
      country_name: "Chad",
      country_code: "TCD",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 41,
      country_name: "Chile",
      country_code: "CHL",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 43,
      country_name: "Colombia",
      country_code: "COL",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 44,
      country_name: "Comoros",
      country_code: "COM",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 45,
      country_name: "Congo",
      country_code: "COG",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 48,
      country_name: "Costa Rica",
      country_code: "CRI",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 50,
      country_name: "Cuba",
      country_code: "CUB",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 52,
      country_name: "Czech Republic",
      country_code: "CZE",
      broadcast_details: {
        broadcasters: ["Nova Sport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Nova_Sport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 46,
      country_name: "Democratic Republic of Congo",
      country_code: "COD",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 54,
      country_name: "Denmark",
      country_code: "DNK",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 55,
      country_name: "Djibouti",
      country_code: "DJI",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 56,
      country_name: "Dominican Republic",
      country_code: "DOM",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 215,
      country_name: "East Timor",
      country_code: "TLS",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 57,
      country_name: "Ecuador",
      country_code: "ECU",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 58,
      country_name: "Egypt",
      country_code: "EGY",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 217,
      country_name: "El Salvador",
      country_code: "SLV",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 60,
      country_name: "Equatorial Guinea",
      country_code: "GNQ",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 61,
      country_name: "Eritrea",
      country_code: "ERI",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 62,
      country_name: "Estonia",
      country_code: "EST",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 63,
      country_name: "Ethiopia",
      country_code: "ETH",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 66,
      country_name: "Finland",
      country_code: "FIN",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 68,
      country_name: "Gabon",
      country_code: "GAB",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 69,
      country_name: "Gambia",
      country_code: "GMB",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 70,
      country_name: "Georgia",
      country_code: "GEO",
      broadcast_details: {
        broadcasters: ["Silknet"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Silknet.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 71,
      country_name: "Germany",
      country_code: "GER",
      broadcast_details: {
        broadcasters: ["Morethansport"],
        s3_urls: [
          " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 72,
      country_name: "Ghana",
      country_code: "GHA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 76,
      country_name: "Grenada",
      country_code: "GRD",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 78,
      country_name: "Guatemala",
      country_code: "GTM",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 80,
      country_name: "Guinea",
      country_code: "GIN",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 81,
      country_name: "Guyana",
      country_code: "GUY",
      broadcast_details: {
        broadcasters: ["ESPN", "ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "2",
    },
    {
      country_id: 82,
      country_name: "Haiti",
      country_code: "HTI",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 83,
      country_name: "Honduras",
      country_code: "HND",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 84,
      country_name: "Hong Kong",
      country_code: "HKG",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 86,
      country_name: "Iceland",
      country_code: "ICE",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 87,
      country_name: "India",
      country_code: "IND",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 88,
      country_name: "Indonesia",
      country_code: "IDN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 89,
      country_name: "Iran",
      country_code: "IRN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 90,
      country_name: "Iraq",
      country_code: "IRQ",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 94,
      country_name: "Italy",
      country_code: "ITA",
      broadcast_details: {
        broadcasters: ["Mola"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Mola.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 95,
      country_name: "Ivory Coast",
      country_code: "CIV",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 96,
      country_name: "Jamaica",
      country_code: "JAM",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 97,
      country_name: "Japan",
      country_code: "JPN",
      broadcast_details: {
        broadcasters: ["Sports Partners"],
        s3_urls: [null],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 99,
      country_name: "Jordan",
      country_code: "JOR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 101,
      country_name: "Kenya",
      country_code: "KEN",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 103,
      country_name: "Kuwait",
      country_code: "KWT",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 105,
      country_name: "Laos",
      country_code: "LAO",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 106,
      country_name: "Latvia",
      country_code: "LVA",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 107,
      country_name: "Lebanon",
      country_code: "LBN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 108,
      country_name: "Liberia",
      country_code: "LBR",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 109,
      country_name: "Libya",
      country_code: "LBY",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 111,
      country_name: "Lithuania",
      country_code: "LTU",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 113,
      country_name: "Macau",
      country_code: "MAC",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 115,
      country_name: "Madagascar",
      country_code: "MDG",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 116,
      country_name: "Malawi",
      country_code: "MWI",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 117,
      country_name: "Malaysia",
      country_code: "MYS",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 118,
      country_name: "Maldives",
      country_code: "MDV",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 119,
      country_name: "Mali",
      country_code: "MLI",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 120,
      country_name: "Malta",
      country_code: "MLT",
      broadcast_details: {
        broadcasters: ["GO"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Go.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 123,
      country_name: "Mauritania",
      country_code: "MRT",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 124,
      country_name: "Mauritius",
      country_code: "MUS",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 125,
      country_name: "Mexico",
      country_code: "MEX",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 131,
      country_name: "Montserrat",
      country_code: "MSR",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 132,
      country_name: "Morocco",
      country_code: "MAR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 133,
      country_name: "Mozambique",
      country_code: "MOZ",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 134,
      country_name: "Myanmar",
      country_code: "MMR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 135,
      country_name: "Namibia",
      country_code: "NAM",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 137,
      country_name: "Nepal",
      country_code: "NPL",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 138,
      country_name: "Netherlands",
      country_code: "NLD",
      broadcast_details: {
        broadcasters: ["Ziggo Sport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Ziggo-Sport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 139,
      country_name: "New Zealand",
      country_code: "NZL",
      broadcast_details: {
        broadcasters: ["Sky New Zealand"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Sky-New-Zealand.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 140,
      country_name: "Nicaragua",
      country_code: "NIC",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 141,
      country_name: "Niger",
      country_code: "NER",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 142,
      country_name: "Nigeria",
      country_code: "NGA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 145,
      country_name: "Norway",
      country_code: "NOR",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 146,
      country_name: "Oman",
      country_code: "OMN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 147,
      country_name: "Pakistan",
      country_code: "PAK",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 149,
      country_name: "Palestine",
      country_code: "PSE",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 150,
      country_name: "Panama",
      country_code: "PAN",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 152,
      country_name: "Paraguay",
      country_code: "PRY",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 153,
      country_name: "Peru",
      country_code: "PER",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 154,
      country_name: "Philippines",
      country_code: "PHL",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 156,
      country_name: "Poland",
      country_code: "POL",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 159,
      country_name: "Qatar",
      country_code: "QAT",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 163,
      country_name: "Rwanda",
      country_code: "RWA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 165,
      country_name: "Saint Lucia",
      country_code: "LCA",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 168,
      country_name: "Saudi Arabia",
      country_code: "SAU",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 170,
      country_name: "Senegal",
      country_code: "SEN",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 173,
      country_name: "Sierra Leone",
      country_code: "SLE",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 174,
      country_name: "Singapore",
      country_code: "SGP",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 175,
      country_name: "Slovakia",
      country_code: "SVK",
      broadcast_details: {
        broadcasters: ["Nova Sport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Nova_Sport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 178,
      country_name: "Somalia",
      country_code: "SOM",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 179,
      country_name: "South Africa",
      country_code: "ZAF",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 160,
      country_name: "South Korea",
      country_code: "KOR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 180,
      country_name: "South Sudan",
      country_code: "SSD",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 181,
      country_name: "Spain",
      country_code: "ESP",
      broadcast_details: {
        broadcasters: ["Telefonica"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Telefonica.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 182,
      country_name: "Sri Lanka",
      country_code: "LKA",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 183,
      country_name: "Sudan",
      country_code: "SDN",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 184,
      country_name: "Suriname",
      country_code: "SUR",
      broadcast_details: {
        broadcasters: ["ESPN", "ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "2",
    },
    {
      country_id: 185,
      country_name: "Swaziland",
      country_code: "SWZ",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 186,
      country_name: "Sweden",
      country_code: "SWE",
      broadcast_details: {
        broadcasters: ["Viaplay"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 187,
      country_name: "Switzerland",
      country_code: "SWI",
      broadcast_details: {
        broadcasters: ["Morethansport"],
        s3_urls: [
          " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 188,
      country_name: "Syria",
      country_code: "SYR",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 189,
      country_name: "Taiwan",
      country_code: "TWN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 191,
      country_name: "Tanzania",
      country_code: "TZA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 192,
      country_name: "Thailand",
      country_code: "THA",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 193,
      country_name: "Togo",
      country_code: "TGO",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 195,
      country_name: "Trinidad and Tobago",
      country_code: "TTO",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 196,
      country_name: "Tunisia",
      country_code: "TUN",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 199,
      country_name: "Turks and Caicos",
      country_code: "TCA",
      broadcast_details: {
        broadcasters: ["ESPN"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 201,
      country_name: "Uganda",
      country_code: "UGA",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 203,
      country_name: "United Arab Emirates",
      country_code: "ARE",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 204,
      country_name: "United Kingdom",
      country_code: "GBR",
      broadcast_details: {
        broadcasters: ["ITV", "PRTV", "TNT Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ITV.webp",
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/PRTV-Blue.webp",
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/TNT-Sports.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "3",
    },
    {
      country_id: 205,
      country_name: "United States",
      country_code: "USA",
      broadcast_details: {
        broadcasters: ["The Rugby Network"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/The-Rugby-Network.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 206,
      country_name: "Uruguay",
      country_code: "URY",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 208,
      country_name: "Venezuela",
      country_code: "VEN",
      broadcast_details: {
        broadcasters: ["ESPN Sur"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 209,
      country_name: "Vietnam",
      country_code: "VNM",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 212,
      country_name: "Yemen",
      country_code: "YEM",
      broadcast_details: {
        broadcasters: ["Premier Sports"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 213,
      country_name: "Zambia",
      country_code: "ZMB",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
    {
      country_id: 214,
      country_name: "Zimbabwe",
      country_code: "ZWE",
      broadcast_details: {
        broadcasters: ["Supersport"],
        s3_urls: [
          "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp",
        ],
      },
      entity_type: "League",
      deal_value_gbp: "110000000.00",
      deal_value_usd: null,
      deal_value_eur: null,
      deal_years: null,
      total_deals: "1",
    },
  ];
  const singleStadiumData = {
    team_stadium: {
      team_name: "Leicester Tigers",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Leicester_Tigers_logo.webp",
      latitude: "52.624167",
      longitude: "-1.133056",
      venue_name: "Mattioli Woods Welford Road",
      capacity: 25849,
      city: "Leicester",
      marker_type: "Team Stadium",
    },
    reference_point: {
      team_name: "London",
      team_logo: null,
      latitude: "51.5007",
      longitude: "-0.1245",
      venue_name: null,
      capacity: null,
      city: null,
      marker_type: "Reference Point",
    },
    stadium_sponsors: {
      sponsor_name: "Mattioli Woods",
      category: "Finance & Banking",
      subcategory: "Wealth Management",
      s3_url:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Leicester+Tigers+T+Webp/Mattioli-Woods.webp",
    },
    stadium_capacity: {
      capacity: 25849,
      rank: "2",
    },
    stadium_name: "Mattioli Woods Welford Road",
    average_attendence: 22075,
  };
  const multipleStadiumData = [
    {
      team_name: "Bath Rugby",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Bath_Rugby_logo.webp",
      latitude: "51.382222",
      longitude: "-2.355278",
      venue_name: "The Recreation Ground",
      capacity: 14509,
      city: "Bath",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Bristol Bears",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Bristol_Bears_logo.svg.webp",
      latitude: "51.440000",
      longitude: "-2.620278",
      venue_name: "Ashton Gate",
      capacity: 27000,
      city: "Bristol",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Exeter Chiefs",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Exeter_Chiefs_logo.webp",
      latitude: "50.709444",
      longitude: "-3.467500",
      venue_name: "Sandy Park",
      capacity: 15600,
      city: "Exeter",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Gloucester Rugby",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Gloucester_logo.webp",
      latitude: "51.871667",
      longitude: "-2.242778",
      venue_name: "Kingsholm",
      capacity: 16115,
      city: "Gloucester",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Harlequins",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Harlequins_logo.webp",
      latitude: "51.450278",
      longitude: "-0.344167",
      venue_name: "Twickenham Stoop",
      capacity: 14800,
      city: "London",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Leicester Tigers",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Leicester_Tigers_logo.webp",
      latitude: "52.624167",
      longitude: "-1.133056",
      venue_name: "Mattioli Woods Welford Road",
      capacity: 25849,
      city: "Leicester",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Newcastle Falcons",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Newcastle_Falcons_logo.webp",
      latitude: "55.018611",
      longitude: "-1.672222",
      venue_name: "Kingston Park",
      capacity: 10200,
      city: "Newcastle upon Tyne",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Northampton Saints",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Northampton_Saints.webp",
      latitude: "52.239444",
      longitude: "-0.919722",
      venue_name: "cinch Stadium at Franklin's Gardens",
      capacity: 15200,
      city: "Northampton",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Sale Sharks",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Sale_Sharks_logo.webp",
      latitude: "53.469444",
      longitude: "-2.375000",
      venue_name: "AJ Bell Stadium",
      capacity: 12000,
      city: "Salford",
      marker_type: "Team Stadium",
    },
    {
      team_name: "Saracens",
      team_logo:
        "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Saracens_logo.webp",
      latitude: "51.603611",
      longitude: "-0.223611",
      venue_name: "StoneX Stadium",
      capacity: 10500,
      city: "London",
      marker_type: "Team Stadium",
    },
    // {
    //   team_name: "Saracens",
    //   team_logo:
    //     "https://foxhams.s3.eu-west-2.amazonaws.com/Premiership+Rugby+Team+Logos+Webp/Saracens_logo.webp",
    //   latitude: "38.889805",
    //   longitude: "-77.009056",
    //   venue_name: "StoneX Stadium",
    //   capacity: 10500,
    //   city: "London",
    //   marker_type: "Team Stadium",
    // },
  ];
  return (
    <div className="App">
      {/* <MapArea /> */}

      {/* <BroadCasterMap data={selectedCountries} /> */}
      {/* <SingleStadium data={singleStadiumData} /> */}
      <MultipleStadium data={multipleStadiumData} />
    </div>
  );
}

export default App;
