import { useState } from "react";
import "./App.css";
import MapArea from "./components/Map";
import BroadCasterMap from "./components/BroadCasterMap";

function App() {
  const selectedCountries=[
    {
        "country_id": 3,
        "country_name": "Algeria",
        "country_code": "DZA",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 6,
        "country_name": "Angola",
        "country_code": "AGO",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 7,
        "country_name": "Anguilla",
        "country_code": "AIA",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 216,
        "country_name": "Antartica",
        "country_code": "ATA",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 8,
        "country_name": "Antigua and Barbuda",
        "country_code": "ATG",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 9,
        "country_name": "Argentina",
        "country_code": "ARG",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 12,
        "country_name": "Australia",
        "country_code": "AUS",
        "broadcasters": "Stan Sport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Stan-Sport.webp"
    },
    {
        "country_id": 13,
        "country_name": "Austria",
        "country_code": "AUT",
        "broadcasters": "Morethansport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp"
    },
    {
        "country_id": 15,
        "country_name": "Bahamas",
        "country_code": "BHS",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 16,
        "country_name": "Bahrain",
        "country_code": "BHR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 17,
        "country_name": "Bangladesh",
        "country_code": "BGD",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 18,
        "country_name": "Barbados",
        "country_code": "BRB",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 21,
        "country_name": "Belize",
        "country_code": "BLZ",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 22,
        "country_name": "Benin",
        "country_code": "BEN",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 23,
        "country_name": "Bermuda",
        "country_code": "BMU",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 24,
        "country_name": "Bhutan",
        "country_code": "BTN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 25,
        "country_name": "Bolivia",
        "country_code": "BOL",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 27,
        "country_name": "Botswana",
        "country_code": "BWA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 28,
        "country_name": "Brazil",
        "country_code": "BRA",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 29,
        "country_name": "British Virgin Islands",
        "country_code": "BVI",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 30,
        "country_name": "Brunei",
        "country_code": "BRN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 32,
        "country_name": "Burkina Faso",
        "country_code": "BFA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 33,
        "country_name": "Burundi",
        "country_code": "BDI",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 35,
        "country_name": "Cambodia",
        "country_code": "KHM",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 36,
        "country_name": "Cameroon",
        "country_code": "CMR",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 37,
        "country_name": "Canada",
        "country_code": "CAN",
        "broadcasters": "Sportsnet",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Sportsnet.webp"
    },
    {
        "country_id": 34,
        "country_name": "Cape Verde",
        "country_code": "CPV",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 38,
        "country_name": "Cayman Islands",
        "country_code": "CYM",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 40,
        "country_name": "Chad",
        "country_code": "TCD",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 41,
        "country_name": "Chile",
        "country_code": "CHL",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 43,
        "country_name": "Colombia",
        "country_code": "COL",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 44,
        "country_name": "Comoros",
        "country_code": "COM",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 45,
        "country_name": "Congo",
        "country_code": "COG",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 48,
        "country_name": "Costa Rica",
        "country_code": "CRI",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 50,
        "country_name": "Cuba",
        "country_code": "CUB",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 52,
        "country_name": "Czech Republic",
        "country_code": "CZE",
        "broadcasters": "Nova Sport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Nova_Sport.webp"
    },
    {
        "country_id": 46,
        "country_name": "Democratic Republic of Congo",
        "country_code": "COD",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 54,
        "country_name": "Denmark",
        "country_code": "DNK",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 55,
        "country_name": "Djibouti",
        "country_code": "DJI",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 56,
        "country_name": "Dominican Republic",
        "country_code": "DOM",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 215,
        "country_name": "East Timor",
        "country_code": "TLS",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 57,
        "country_name": "Ecuador",
        "country_code": "ECU",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 58,
        "country_name": "Egypt",
        "country_code": "EGY",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 217,
        "country_name": "El Salvador",
        "country_code": "SLV",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 60,
        "country_name": "Equatorial Guinea",
        "country_code": "GNQ",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 61,
        "country_name": "Eritrea",
        "country_code": "ERI",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 62,
        "country_name": "Estonia",
        "country_code": "EST",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 63,
        "country_name": "Ethiopia",
        "country_code": "ETH",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 66,
        "country_name": "Finland",
        "country_code": "FIN",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 68,
        "country_name": "Gabon",
        "country_code": "GAB",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 69,
        "country_name": "Gambia",
        "country_code": "GMB",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 70,
        "country_name": "Georgia",
        "country_code": "GEO",
        "broadcasters": "Silknet",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Silknet.webp"
    },
    {
        "country_id": 71,
        "country_name": "Germany",
        "country_code": "GER",
        "broadcasters": "Morethansport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp"
    },
    {
        "country_id": 72,
        "country_name": "Ghana",
        "country_code": "GHA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 76,
        "country_name": "Grenada",
        "country_code": "GRD",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 78,
        "country_name": "Guatemala",
        "country_code": "GTM",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 80,
        "country_name": "Guinea",
        "country_code": "GIN",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 81,
        "country_name": "Guyana",
        "country_code": "GUY",
        "broadcasters": "ESPN, ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "2",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 82,
        "country_name": "Haiti",
        "country_code": "HTI",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 83,
        "country_name": "Honduras",
        "country_code": "HND",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 84,
        "country_name": "Hong Kong",
        "country_code": "HKG",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 86,
        "country_name": "Iceland",
        "country_code": "ICE",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 87,
        "country_name": "India",
        "country_code": "IND",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 88,
        "country_name": "Indonesia",
        "country_code": "IDN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 89,
        "country_name": "Iran",
        "country_code": "IRN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 90,
        "country_name": "Iraq",
        "country_code": "IRQ",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 94,
        "country_name": "Italy",
        "country_code": "ITA",
        "broadcasters": "Mola",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Mola.webp"
    },
    {
        "country_id": 95,
        "country_name": "Ivory Coast",
        "country_code": "CIV",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 96,
        "country_name": "Jamaica",
        "country_code": "JAM",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 97,
        "country_name": "Japan",
        "country_code": "JPN",
        "broadcasters": "Sports Partners",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": null
    },
    {
        "country_id": 99,
        "country_name": "Jordan",
        "country_code": "JOR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 101,
        "country_name": "Kenya",
        "country_code": "KEN",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 103,
        "country_name": "Kuwait",
        "country_code": "KWT",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 105,
        "country_name": "Laos",
        "country_code": "LAO",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 106,
        "country_name": "Latvia",
        "country_code": "LVA",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 107,
        "country_name": "Lebanon",
        "country_code": "LBN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 108,
        "country_name": "Liberia",
        "country_code": "LBR",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 109,
        "country_name": "Libya",
        "country_code": "LBY",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 111,
        "country_name": "Lithuania",
        "country_code": "LTU",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 113,
        "country_name": "Macau",
        "country_code": "MAC",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 115,
        "country_name": "Madagascar",
        "country_code": "MDG",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 116,
        "country_name": "Malawi",
        "country_code": "MWI",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 117,
        "country_name": "Malaysia",
        "country_code": "MYS",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 118,
        "country_name": "Maldives",
        "country_code": "MDV",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 119,
        "country_name": "Mali",
        "country_code": "MLI",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 120,
        "country_name": "Malta",
        "country_code": "MLT",
        "broadcasters": "GO",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Go.webp"
    },
    {
        "country_id": 123,
        "country_name": "Mauritania",
        "country_code": "MRT",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 124,
        "country_name": "Mauritius",
        "country_code": "MUS",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 125,
        "country_name": "Mexico",
        "country_code": "MEX",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 131,
        "country_name": "Montserrat",
        "country_code": "MSR",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 132,
        "country_name": "Morocco",
        "country_code": "MAR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 133,
        "country_name": "Mozambique",
        "country_code": "MOZ",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 134,
        "country_name": "Myanmar",
        "country_code": "MMR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 135,
        "country_name": "Namibia",
        "country_code": "NAM",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 137,
        "country_name": "Nepal",
        "country_code": "NPL",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 138,
        "country_name": "Netherlands",
        "country_code": "NLD",
        "broadcasters": "Ziggo Sport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Ziggo-Sport.webp"
    },
    {
        "country_id": 139,
        "country_name": "New Zealand",
        "country_code": "NZL",
        "broadcasters": "Sky New Zealand",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Sky-New-Zealand.webp"
    },
    {
        "country_id": 140,
        "country_name": "Nicaragua",
        "country_code": "NIC",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 141,
        "country_name": "Niger",
        "country_code": "NER",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 142,
        "country_name": "Nigeria",
        "country_code": "NGA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 145,
        "country_name": "Norway",
        "country_code": "NOR",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 146,
        "country_name": "Oman",
        "country_code": "OMN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 147,
        "country_name": "Pakistan",
        "country_code": "PAK",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 149,
        "country_name": "Palestine",
        "country_code": "PSE",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 150,
        "country_name": "Panama",
        "country_code": "PAN",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 152,
        "country_name": "Paraguay",
        "country_code": "PRY",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 153,
        "country_name": "Peru",
        "country_code": "PER",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 154,
        "country_name": "Philippines",
        "country_code": "PHL",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 156,
        "country_name": "Poland",
        "country_code": "POL",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 159,
        "country_name": "Qatar",
        "country_code": "QAT",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 163,
        "country_name": "Rwanda",
        "country_code": "RWA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 165,
        "country_name": "Saint Lucia",
        "country_code": "LCA",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 168,
        "country_name": "Saudi Arabia",
        "country_code": "SAU",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 170,
        "country_name": "Senegal",
        "country_code": "SEN",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 173,
        "country_name": "Sierra Leone",
        "country_code": "SLE",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 174,
        "country_name": "Singapore",
        "country_code": "SGP",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 175,
        "country_name": "Slovakia",
        "country_code": "SVK",
        "broadcasters": "Nova Sport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Nova_Sport.webp"
    },
    {
        "country_id": 178,
        "country_name": "Somalia",
        "country_code": "SOM",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 179,
        "country_name": "South Africa",
        "country_code": "ZAF",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 160,
        "country_name": "South Korea",
        "country_code": "KOR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 180,
        "country_name": "South Sudan",
        "country_code": "SSD",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 181,
        "country_name": "Spain",
        "country_code": "ESP",
        "broadcasters": "Telefonica",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Telefonica.webp"
    },
    {
        "country_id": 182,
        "country_name": "Sri Lanka",
        "country_code": "LKA",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 183,
        "country_name": "Sudan",
        "country_code": "SDN",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 184,
        "country_name": "Suriname",
        "country_code": "SUR",
        "broadcasters": "ESPN, ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "2",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 185,
        "country_name": "Swaziland",
        "country_code": "SWZ",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 186,
        "country_name": "Sweden",
        "country_code": "SWE",
        "broadcasters": "Viaplay",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/viaplay-logo.webp"
    },
    {
        "country_id": 187,
        "country_name": "Switzerland",
        "country_code": "SWI",
        "broadcasters": "Morethansport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": " https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Morethansports.webp"
    },
    {
        "country_id": 188,
        "country_name": "Syria",
        "country_code": "SYR",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 189,
        "country_name": "Taiwan",
        "country_code": "TWN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 191,
        "country_name": "Tanzania",
        "country_code": "TZA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 192,
        "country_name": "Thailand",
        "country_code": "THA",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 193,
        "country_name": "Togo",
        "country_code": "TGO",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 195,
        "country_name": "Trinidad and Tobago",
        "country_code": "TTO",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 196,
        "country_name": "Tunisia",
        "country_code": "TUN",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 199,
        "country_name": "Turks and Caicos",
        "country_code": "TCA",
        "broadcasters": "ESPN",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 201,
        "country_name": "Uganda",
        "country_code": "UGA",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 203,
        "country_name": "United Arab Emirates",
        "country_code": "ARE",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 204,
        "country_name": "United Kingdom",
        "country_code": "GBR",
        "broadcasters": "ITV, PRTV, TNT Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "3",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ITV.webp, https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/PRTV-Blue.webp, https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/TNT-Sports.webp"
    },
    {
        "country_id": 205,
        "country_name": "United States",
        "country_code": "USA",
        "broadcasters": "The Rugby Network",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/The-Rugby-Network.webp"
    },
    {
        "country_id": 206,
        "country_name": "Uruguay",
        "country_code": "URY",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 208,
        "country_name": "Venezuela",
        "country_code": "VEN",
        "broadcasters": "ESPN Sur",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/ESPN.webp"
    },
    {
        "country_id": 209,
        "country_name": "Vietnam",
        "country_code": "VNM",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 212,
        "country_name": "Yemen",
        "country_code": "YEM",
        "broadcasters": "Premier Sports",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/Premier-Sports-1.webp"
    },
    {
        "country_id": 213,
        "country_name": "Zambia",
        "country_code": "ZMB",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    },
    {
        "country_id": 214,
        "country_name": "Zimbabwe",
        "country_code": "ZWE",
        "broadcasters": "Supersport",
        "entity_types": "League",
        "total_deal_value_gbp": "110000000.00",
        "total_deal_value_usd": null,
        "total_deal_value_eur": null,
        "deal_years": null,
        "total_deals": "1",
        "s3_urls": "https://foxhams.s3.eu-west-2.amazonaws.com/Broadcasters+T+1/SuperSport.webp"
    }
]
  return (
    <div className="App">
      {/* <MapArea /> */}
      
      <BroadCasterMap data={selectedCountries}/>
    </div>
  );
}

export default App;
